# In this directory, run the following command to build this builder.
# $ gcloud builds submit .

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/nix-cachix:latest', '-f', 'Dockerfile', '.']

images:
  - 'gcr.io/${PROJECT_ID}/nix-cachix:latest'
